// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Presence struct {
	ID        int32       `json:"id"`
	UserID    int32       `json:"user_id"`
	Date      time.Time   `json:"date"`
	StatusAm  pgtype.Text `json:"status_am"`
	StatusPm  pgtype.Text `json:"status_pm"`
	CreatedAt time.Time   `json:"created_at"`
}

type Team struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type TeamMember struct {
	ID           int32       `json:"id"`
	TeamID       int32       `json:"team_id"`
	UserID       int32       `json:"user_id"`
	Productivity pgtype.Int4 `json:"productivity"`
	CreatedAt    time.Time   `json:"created_at"`
}

type User struct {
	ID        int32       `json:"id"`
	Name      string      `json:"name"`
	Email     string      `json:"email"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
	CreatedAt time.Time   `json:"created_at"`
}
