// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package store

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const addUserToTeam = `-- name: AddUserToTeam :one
INSERT INTO team_members (team_id, user_id, productivity)
VALUES ($1, $2, $3)
ON CONFLICT (team_id, user_id) DO UPDATE SET productivity = EXCLUDED.productivity
RETURNING id, created_at
`

type AddUserToTeamParams struct {
	TeamID       int32       `json:"team_id"`
	UserID       int32       `json:"user_id"`
	Productivity pgtype.Int4 `json:"productivity"`
}

type AddUserToTeamRow struct {
	ID        int32     `json:"id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) AddUserToTeam(ctx context.Context, arg AddUserToTeamParams) (AddUserToTeamRow, error) {
	row := q.db.QueryRow(ctx, addUserToTeam, arg.TeamID, arg.UserID, arg.Productivity)
	var i AddUserToTeamRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (name) VALUES ($1) RETURNING id, created_at
`

type CreateTeamRow struct {
	ID        int32     `json:"id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateTeam(ctx context.Context, name string) (CreateTeamRow, error) {
	row := q.db.QueryRow(ctx, createTeam, name)
	var i CreateTeamRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email, avatar_url) VALUES ($1, $2, $3) RETURNING id, created_at
`

type CreateUserParams struct {
	Name      string      `json:"name"`
	Email     string      `json:"email"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
}

type CreateUserRow struct {
	ID        int32     `json:"id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Name, arg.Email, arg.AvatarUrl)
	var i CreateUserRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const deleteTeam = `-- name: DeleteTeam :exec
DELETE FROM teams WHERE id = $1
`

func (q *Queries) DeleteTeam(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteTeam, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getPresence = `-- name: GetPresence :many
SELECT id, user_id, to_char(date, 'YYYY-MM-DD') as date, COALESCE(status_am, '') as status_am, COALESCE(status_pm, '') as status_pm, created_at 
FROM presence 
WHERE date >= $1::date AND date <= $2::date
`

type GetPresenceParams struct {
	Column1 time.Time `json:"column_1"`
	Column2 time.Time `json:"column_2"`
}

type GetPresenceRow struct {
	ID        int32     `json:"id"`
	UserID    int32     `json:"user_id"`
	Date      string    `json:"date"`
	StatusAm  string    `json:"status_am"`
	StatusPm  string    `json:"status_pm"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) GetPresence(ctx context.Context, arg GetPresenceParams) ([]GetPresenceRow, error) {
	rows, err := q.db.Query(ctx, getPresence, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPresenceRow
	for rows.Next() {
		var i GetPresenceRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Date,
			&i.StatusAm,
			&i.StatusPm,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeamMembers = `-- name: GetTeamMembers :many
SELECT tm.id, tm.team_id, tm.user_id, tm.productivity, tm.created_at, u.name as user_name
FROM team_members tm
JOIN users u ON tm.user_id = u.id
WHERE tm.team_id = $1
`

type GetTeamMembersRow struct {
	ID           int32       `json:"id"`
	TeamID       int32       `json:"team_id"`
	UserID       int32       `json:"user_id"`
	Productivity pgtype.Int4 `json:"productivity"`
	CreatedAt    time.Time   `json:"created_at"`
	UserName     string      `json:"user_name"`
}

func (q *Queries) GetTeamMembers(ctx context.Context, teamID int32) ([]GetTeamMembersRow, error) {
	rows, err := q.db.Query(ctx, getTeamMembers, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTeamMembersRow
	for rows.Next() {
		var i GetTeamMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.UserID,
			&i.Productivity,
			&i.CreatedAt,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeams = `-- name: GetTeams :many
SELECT id, name, created_at FROM teams ORDER BY name
`

func (q *Queries) GetTeams(ctx context.Context) ([]Team, error) {
	rows, err := q.db.Query(ctx, getTeams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserTeams = `-- name: GetUserTeams :many
SELECT tm.id, tm.team_id, tm.user_id, tm.productivity, tm.created_at, t.name as team_name
FROM team_members tm
JOIN teams t ON tm.team_id = t.id
WHERE tm.user_id = $1
`

type GetUserTeamsRow struct {
	ID           int32       `json:"id"`
	TeamID       int32       `json:"team_id"`
	UserID       int32       `json:"user_id"`
	Productivity pgtype.Int4 `json:"productivity"`
	CreatedAt    time.Time   `json:"created_at"`
	TeamName     string      `json:"team_name"`
}

func (q *Queries) GetUserTeams(ctx context.Context, userID int32) ([]GetUserTeamsRow, error) {
	rows, err := q.db.Query(ctx, getUserTeams, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserTeamsRow
	for rows.Next() {
		var i GetUserTeamsRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.UserID,
			&i.Productivity,
			&i.CreatedAt,
			&i.TeamName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsers = `-- name: GetUsers :many
SELECT id, name, email, COALESCE(avatar_url, '') as avatar_url, created_at FROM users
`

type GetUsersRow struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	Email     string    `json:"email"`
	AvatarUrl string    `json:"avatar_url"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) GetUsers(ctx context.Context) ([]GetUsersRow, error) {
	rows, err := q.db.Query(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersRow
	for rows.Next() {
		var i GetUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.AvatarUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUserFromTeam = `-- name: RemoveUserFromTeam :exec
DELETE FROM team_members WHERE team_id = $1 AND user_id = $2
`

type RemoveUserFromTeamParams struct {
	TeamID int32 `json:"team_id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) RemoveUserFromTeam(ctx context.Context, arg RemoveUserFromTeamParams) error {
	_, err := q.db.Exec(ctx, removeUserFromTeam, arg.TeamID, arg.UserID)
	return err
}

const upsertPresence = `-- name: UpsertPresence :one
INSERT INTO presence (user_id, date, status_am, status_pm)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, date) DO UPDATE SET 
    status_am = EXCLUDED.status_am,
    status_pm = EXCLUDED.status_pm
RETURNING id, created_at
`

type UpsertPresenceParams struct {
	UserID   int32       `json:"user_id"`
	Date     time.Time   `json:"date"`
	StatusAm pgtype.Text `json:"status_am"`
	StatusPm pgtype.Text `json:"status_pm"`
}

type UpsertPresenceRow struct {
	ID        int32     `json:"id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) UpsertPresence(ctx context.Context, arg UpsertPresenceParams) (UpsertPresenceRow, error) {
	row := q.db.QueryRow(ctx, upsertPresence,
		arg.UserID,
		arg.Date,
		arg.StatusAm,
		arg.StatusPm,
	)
	var i UpsertPresenceRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}
