// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"
)

type Querier interface {
	AddUserToTeam(ctx context.Context, arg AddUserToTeamParams) (AddUserToTeamRow, error)
	CreateTeam(ctx context.Context, name string) (CreateTeamRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteTeam(ctx context.Context, id int32) error
	DeleteUser(ctx context.Context, id int32) error
	GetPresence(ctx context.Context, arg GetPresenceParams) ([]GetPresenceRow, error)
	GetTeamMembers(ctx context.Context, teamID int32) ([]GetTeamMembersRow, error)
	GetTeams(ctx context.Context) ([]Team, error)
	GetUserTeams(ctx context.Context, userID int32) ([]GetUserTeamsRow, error)
	GetUsers(ctx context.Context) ([]GetUsersRow, error)
	RemoveUserFromTeam(ctx context.Context, arg RemoveUserFromTeamParams) error
	UpsertPresence(ctx context.Context, arg UpsertPresenceParams) (UpsertPresenceRow, error)
}

var _ Querier = (*Queries)(nil)
